### ISSUE TITLE
Remove Poolsize chart since it looks quite useless

### ISSUE THREAD

**Issue by Dyrk** [Dyrk/decred-dashboard#15]

**Comment by eshriek** [comment]
Poolsize chart would look more useful if it showed the target plus or minus 1000 or 2000. Only show the range 40000-44000. Awesome work btw, using it every day.

**Comment by Dyrk** [comment]
Replaced by Tickets History chart: https://github.com/Dyrk/decred-dashboard/commit/b534fd84657a35048bf2327242a09e6065f1373d
