### ISSUE TITLE
AVG FEES IN MEMPOOL below minimum fee

### ISSUE THREAD

**Issue by jyap808** [Dyrk/decred-dashboard#3]
Currently showing average fee of 0.0469 DCR.

This doesn't seem right. Vote stake transactions have 0 transfer fee which is probably pulling the average fee down. The Vote stake transactions should be ignored in this case when calculating average fee.

**Comment by Dyrk** [comment]
@jyap808 as far as I know 0.05 is not minimum fee anymore. Also parser already ignores all 0/null fees transactions: [initial commit](https://github.com/Dyrk/decred-dashboard/commit/918d50bb9c7a7f626b02f9686a81de98101a5e49#diff-78c12f5adc1848d13b1c6f07055d996eR310).

Here is mempool-parser output example. As you can see it found 11 transactions in the mempool, but only 2 of them had non-zero fee: 0.05 and 0.0129. Nine other transactions were not included in the final calculations.
`
Parse 1 / 11 transaction: 6abcc269c8de1a107df101ea00d93cb4ce24c8cdfefe916c4af13bd8e7f23599
Parse 1 / 10 transaction: 043166a3202a2173e5e561b947d3e9dd9a6157961d41716f868b93b0b81f30d8
Fees:  0.05
Parse 2 / 10 transaction: 001d7431eb83f989cd3500c2c5fd786b3bc199a38ceb95a98c524d402a53c9b2
Fees:  0.0129
Parse 3 / 10 transaction: 08adb0db1873b3b5e38e46dde35eac9e59d78e27849edf594c1bd65034dddf1d
Parse 3 / 9 transaction: a5c844998b08b6c681b5966934092ad17487f598ac2a959d632922338e2fd46a
Parse 3 / 8 transaction: def256e39bce5282312f1bb8bd301cd70e51f6ad7820fe3ab721b72fe732f335
Parse 3 / 7 transaction: 54ea17474915e793b3642287cc6997995ca32e2de611b3099b55813708ba758b
Parse 3 / 6 transaction: 09a248e2ab08c81de3df5b5244d34ab64144193b2713f41785f42e82ef2d1fae
Parse 3 / 5 transaction: c9ba8ed979d866cbf484d1693776eb12c400fa28c7e952b790d79b20ca0888db
Parse 3 / 4 transaction: 5c03a5581a3431a62922dc6e0d28151fde61b3d1f37841f5c16f771da7c06c37
Parse 3 / 3 transaction: 5f845bba4b7e737d75ed58cef29ba75753e8ccb33eb271fee47638995f604a9a
2 transactions processed
Total Fees:0.0629
Avg Fee:0.03145
Max Fee:0.05
`
