### ISSUE TITLE
New APIs endpoints

### ISSUE THREAD

**Issue by JonathanVeg** [Dyrk/decred-dashboard#30]
Hi. As we spoke at slack, I need some info from your API.

I need:
- Stake Reward;
- Blocks to adjust;
- Pow Reward;

- Locked DCRs;
- Avg Ticket Price;

That info are in your site but I was not able to found in API endpoints.

Thanks!!

**Comment by Dyrk** [comment]
Hi @JonathanVeg I've added this data to https://dcrstats.com/api/v1/get_stats:
```
vote_reward
pos_adjustment
pow_reward
ticketpoolvalue
avg_ticket_price
```
