### ISSUE TITLE
TO DO: Estimated ticket price

### ISSUE THREAD

**Issue by Dyrk** [Dyrk/decred-dashboard#5]
1. Port this to JS
https://github.com/decred/dcrd/blob/master/blockchain/difficulty.go
2. Update block parser and DB to support number of SStx per block

**Comment by bezformy** [comment]
Hey,
I think I have the `calcNextRequiredStakeDifficulty` function converted to js. I'm not sure if anything else is importand from the `difficulty.go` file.
For the `7776` block my version gives `9.25503883` which is exactly the current ticked price. And for the current `7841` block it gives an estimation of `10.69852157` which seems reasonable to me.
It is a standalone script at the moment and I need to clean it up a little, but I can share if you are interested.

**Comment by Dyrk** [comment]
Hey @bezformy,

sounds great. Of course I'm interested, please share it ;)

**Comment by bezformy** [comment]
Okay, so here it is:
https://gist.github.com/bezformy/2d5326675122559423e3

You need to:
```bash
npm install big-integer
```
And create an empty `node_cache.json` file (the script caches the previous blocks, so I don't have to wait a bunch of time every time I run it), then simply run:
```bash
node index.js
```
Wait until it finishes and you'll get something like this:
```
[ null, 8.41328204 ]
```

Right now it uses `execSync` because it was easier to implement it this way, I basically just converted the go stuff to js and haven't touched anything else. But if you'd like I could make this whole thing async and send a pull request.

**Comment by Dyrk** [comment]
Hi @bezformy 
I've added your script here:
https://github.com/Dyrk/decred-dashboard/blob/master/bin/difficulty.js

Since it synchronous, I'm running it as separate nodejs process (PM2 reports that it uses ~ 100mb of ram).

I made these small changes:
1. Use dcrstat database instead of hardcoded best block hash.
However, even if you run it locally, you can use RPC call `getbestblockhash`, see this bash script example:
```
blockhash=$(dcrctl getbestblockhash);
dcrctl getblock $blockhash
```
2. Cron job (each first day of the month) to replace content of node_cache.json with empty object {}. We need maximum 144 * 20 blocks, so there is no need to keep that cache file extremely big.

**Comment by bezformy** [comment]
Hey,
I noticed it about 10 minutes ago. You should be able to make it async. You have all the data in the database so the only thing you have to do is to get the last `144 * 20 = 2880` blocks, and run the script on them. It would use a lot less memory that way and wouldn't block the process. Ohh, and you wouldn't need the `node_cache.json` file either.

**Comment by Dyrk** [comment]
Decred devs introduced new RPC call: `estimatestakediff` with min, max, and best estimate for next stake difficulty.
So now I am using it for "Estimated Ticket Price". Issue closed in https://github.com/Dyrk/decred-dashboard/commit/662f09ece1a19e39bd30c3a02defc472c8b7a309
