### ISSUE TITLE
Display active network

### ISSUE THREAD

**Issue by SG-O** [Dyrk/decred-dashboard#8]
I don't know if this would be possible, but it would be great if there was a list of all nodes that are listening. It would be even better if there would be a visualization on a world map.

**Comment by Dyrk** [comment]
Hi @SG-O,

thank you for the request. Finaly I finished this functionality: [commit #2f586fd25](https://github.com/Dyrk/decred-dashboard/commit/2f586fd25532e6c57208f1f7db7a046e49abc160)
See live version here: https://dcrstats.com/map
