### ISSUE TITLE
Historical graph of hash rate

### ISSUE THREAD

**Issue by AlanBarber** [Dyrk/decred-dashboard#9]
Another useful historical graph would be the hash rate. It would be a good indicator of health of the network to be able to visualize how much hardware is out there mining.

**Comment by Dyrk** [comment]
Hi @AlanBarber,
thank you for your feedback. This feature was deployed today, including:
1. Network Hashrate Distribution
2. Historical Hashrate Chart
3. Historucal Difficulty Chart.

Now you can check it here: https://dcrstats.com/pow
